class userstats:
    def __init__(self, json: dict):
        self.playtime = json["TotalPlayTimeInMs"]
        self.npcsattacked = json["NpcsAttacked"]
        self.playersattacked = json["PlayersAttacked"]
        self.timesattacked = json["TimesAttacked"]
        self.starbasesdestroyed = json["StarbasesDestroyed"]
        self.buildingsdestroyed = json["BuildingsDestroyed"]
        self.damagedone = json["DamageDoneInAttacks"]
        self.obstaclesrecycled = json["ObstaclesRecycled"]
        self.coinsspent = json["CoinsSpent"]
        self.mineralsspent = json["MineralsSpent"]
        self.chipsspent = json["ChipsSpent"]
        self.coinloot = json["CoinsFromAttacks"]
        self.mineralloot = json["MineralsFromAttacks"]
        self.scoreloot = json["ScoreFromAttacks"]
        self.utilitiesused = json["UtilityUsed"]
        self.nukesused = json["NukesUsed"]
        self.troopstrained = json["TroopsTrained"]
        self.troopsizedonated = json["TroopSizesDonated"]
        self.helpclicksused = json["FriendsHelped"]
        self.giftsreceived = json["GiftsReceived"]
        self.giftssent = json["GiftsSent"]
        self.coloniesmoved = json["ColoniesMoved"]
        self.starsvisited = json["StarsVisited"]
